>P1;7y6mC
structureX:7y6mC:1: : 290  : :  : : -1.00 :-1.00
-------------------KETPESIQEIKAPELWSSGFKGKGITIAVLDTGCDTEHPDL
KDQIIGGKNFTDDDDGDAENVKDYNGHGTHVAGTIAATDQNG-GILGVAPEAKLLIVKVL
GGE-----NGSGKYEWIIDGINYAAE------QKVDIISMSLGGPSNEPALQEAIQNAVK
SGVLVVCAAGNEGDGDERTEEFSYPAAYNEVIAVGSVSLARESSEFSNANKEIDLVAPGE
DILSTLPNHKYGRLTGTSMAAPHVSGALAIIKNAEEEAFQRKLTEPEIYAQLVRRTLPLK
QSKALVGNGFLYLTAPDVLLE----------*
>P1;P11018
structureX:sp|P11018|ISP1_BACSU:1: : 319  : :  : : -1.00 :-1.00
MNGEIRLIPYVTNEQIMDVNELPEGIKVIKAPEMWAKGVKGKNIKVAVLDTGCDTSHPDL
KNQIIGGKNFTDDDGGKEDAISDYNGHGTHVAGTIAANDSNG-GIAGVAPEASLLIVKVL
GGE-----NGSGQYEWIINGINYAVE------QKVDIISMSLGGPSDVPELKEAVKNAVK
NGVLVVCAAGNEGDGDERTEELSYPAAYNEVIAVGSVSVARELSEFSNANKEIDLVAPGE
NILSTLPNKKYGKLTGTSMAAPHVSGALALIKSYEEESFQRKLSESEVFAQLIRRTLPLD
IAKTLAGNGFLYLTAPDELAEKAEQSHLLTL*
>P1;7xr8A
structureX:7xr8A:1: : 292  : :  : : -1.00 :-1.00
---TIRLIPFKIEEKLESVKEIPEGVNMVQAPEIWKEGIRGKDIVIAVIDTGCDRDHPDL
KDRIIGGRNFTTDDNGDVDNYSDYNGHGTHVAGTIAATENDQ-GVVGVAPEAKLLILKVL
ANDPNNPGSATGKYEWIVNAINYAID------QKVDIISMSLGGPSDVPELHQAVKRAVE
NNILVVCAAG----------ELSYPAAYNEVISVGAISLDG--------QIEIDVVAPGE
KILSTIPGGKFAVFSGTSMATPHVSGALALIKQLSEKEFERNLTEPELYAQLIKRTMPLG
FPKALEGNGLVYLTAPNLLS-----------*
>P1;6f9mA
structureX:6f9mA:1: : 293  : :  : : -1.00 :-1.00
---NIHLIPYRVEQVTAAPPRIPEGVRMIQAPELWESAEHGKGNVVAVLDTGCQTDHPDL
TARIAGGRNFTHDDGGDPERFEDYNGHGTHVAGTVAASLRDEEGVVGVAPLADLLVVKVL
DKE------GSGSYEGIIAGIHYAIDWRGPEGQKTTVISMSLGGPEDHPELYEAVKRAVD
AGIPVICAAG--------TDEFAYPGAYGEVIQVGAVDFDRR-------INEIDLVAPGI
NIYSTYLEGKYASLSGTSMATPHVSGALALIRNISEREFDRELTEAELYAQLVRRTIPLG
YPKTAEGNGLLALDILN--------------*
>P1;2wv7A
structureX:2wv7A:1: : 298  : :  : : -1.00 :-1.00
---KFRLIPYKQVDKVSALSEVPMGVEIVEAPAVWRASAKGAGQIIGVIDTGCQVDHPDL
AERIIGGVNLTTDYGGDETNFSDNNGHGTHVAGTVAAAETGS-GVVGVAPKADLFIIKAL
SGD------GSGEMGWIAKAIRYAVDWRGPKGEQMRIITMSLGGPTDSEELHDAVKYAVS
NNVSVVCAAG--------NNEFAYPAAYNEVIAVGAVDFDLRL--------EIDIVAPGV
GIKSTYLDSGYAELSGTAMAAPHVAGALALIINLAEDAFKRSLSETEIYAQLVRRATPIG
FTAQAEGNGFLTLDLVERITGQFT-------*
>P1;2x8jA
structureX:2x8jA:1: : 302  : :  : : -1.00 :-1.00
--RKFRLIPYKQVDKVSALSEVPMGVEIVEAPAVWRASAKGAGQIIGVIDTGCQVDHPDL
AERIIGGVNLTTDYGGDETNFSDNNGHGTHVAGTVAAAETGS-GVVGVAPKADLFIIKAL
SGD------GSGEMGWIAKAIRYAVDWRGPKGEQMRIITMSLGGPTDSEELHDAVKYAVS
NNVSVVAAG----------NEFAYPAAYNEVIAVGAVDFDLRLSDF---NEEIDIVAPGV
GIKSTYLDSGYAELSGTAMAAPHVAGALALIINLAEDAFKRSLSETEIYAQLVRRATPIG
FTAQAEGNGFLTLDLVERITGQFT-------*
