>P1;2wv7A
structureX:2wv7A:1: : 298  : :  : : -1.00 :-1.00
---KFRLIPYKQVDKVSALSEVPMGVEIVEAPAVWRASAKGAGQIIGVIDTGCQVDHPDL
AERIIGGVNLTTDYGGDETNFSDNNGHGTHVAGTVAAAE-TG-SGVVGVAPKADLFIIKA
LS-GD------GSGEMGWIAKAIRYAVDWRGPKGEQMRIITMSLGGPTDSEELHDAVKYA
VSNNVSVVCAAGNN----------EFAYPAAYNEVIAVGAVDFDLR----LE----IDIV
APGVGIKSTYLDSGYAELSGTAMAAPHVAGALALIINLAEDAFKRSLSETEIYAQLVRRA
TPIGFTAQAEGNGFLTLDLVERITGQFT--------*
>P1;2x8jA
structureX:2x8jA:1: : 302  : :  : : -1.00 :-1.00
--RKFRLIPYKQVDKVSALSEVPMGVEIVEAPAVWRASAKGAGQIIGVIDTGCQVDHPDL
AERIIGGVNLTTDYGGDETNFSDNNGHGTHVAGTVAAAE-TG-SGVVGVAPKADLFIIKA
LS-GD------GSGEMGWIAKAIRYAVDWRGPKGEQMRIITMSLGGPTDSEELHDAVKYA
VSNNVSVV-AA-GN----------EFAYPAAYNEVIAVGAVDFDLRLSD-FN--EEIDIV
APGVGIKSTYLDSGYAELSGTAMAAPHVAGALALIINLAEDAFKRSLSETEIYAQLVRRA
TPIGFTAQAEGNGFLTLDLVERITGQFT--------*
>P1;6f9mA
structureX:6f9mA:1: : 293  : :  : : -1.00 :-1.00
---NIHLIPYRVEQVTAAPPRIPEGVRMIQAPELWESAEHGKGNVVAVLDTGCQTDHPDL
TARIAGGRNFTHDDGGDPERFEDYNGHGTHVAGTVAASL-RDEEGVVGVAPLADLLVVKV
LD-KE------GSGSYEGIIAGIHYAIDWRGPEGQKTTVISMSLGGPEDHPELYEAVKRA
VDAGIPVICAA-GT---------DEFAYPGAYGEVIQVGAVDFDRR----IN---EIDLV
APGINIYSTYLEGKYASLSGTSMATPHVSGALALIRNISEREFDRELTEAELYAQLVRRT
IPLGYPKTAEGNGLLALDIL-----N----------*
>P1;7xr8A
structureX:7xr8A:1: : 292  : :  : : -1.00 :-1.00
---TIRLIPFKIEEKLESVKEIPEGVNMVQAPEIWKEGIRGKDIVIAVIDTGCDRDHPDL
KDRIIGGRNFTTDDNGDVDNYSDYNGHGTHVAGTIAATE-ND-QGVVGVAPEAKLLILKV
LA-NDPNNPGSATGKYEWIVNAINYAIDQ------KVDIISMSLGGPSDVPELHQAVKRA
VENNILVVCAA-GE-----------LSYPAAYNEVISVGAISLDGQ----IE----IDVV
APGEKILSTIPGGKFAVFSGTSMATPHVSGALALIKQLSEKEFERNLTEPELYAQLIKRT
MPLGFPKALEGNGLVYLTAPNLLS------------*
>P1;7y6mC
structureX:7y6mC:1: : 290  : :  : : -1.00 :-1.00
-------------------KETPESIQEIKAPELWSSGFKGKGITIAVLDTGCDTEHPDL
KDQIIGGKNFTDDDDGDAENVKDYNGHGTHVAGTIAATDQNG--GILGVAPEAKLLIVKV
LGGEN------GSGKYEWIIDGINYAAEQ------KVDIISMSLGGPSNEPALQEAIQNA
VKSGVLVVCAAGNEGDGDERTEEF--SYPAAYNEVIAVGSVSLARESSEFSNANKEIDLV
APGEDILSTLPNHKYGRLTGTSMAAPHVSGALAIIKNAEEEAFQRKLTEPEIYAQLVRRT
LPLKQSKALVGNGFLYLTAPDVLL-E----------*
>P1;P11018
structureX:sp|P11018|ISP1_BACSU:1: : 319  : :  : : -1.00 :-1.00
MNGEIRLIPYVTNEQIMDVNELPEGIKVIKAPEMWAKGVKGKNIKVAVLDTGCDTSHPDL
KNQIIGGKNFTDDDGGKEDAISDYNGHGTHVAGTIAANDSNG--GIAGVAPEASLLIVKV
LGGEN------GSGQYEWIINGINYAVEQ------KVDIISMSLGGPSDVPELKEAVKNA
VKNGVLVVCAAGNEGDGDERTEEL--SYPAAYNEVIAVGSVSVARELSEFSNANKEIDLV
APGENILSTLPNKKYGKLTGTSMAAPHVSGALALIKSYEEESFQRKLSESEVFAQLIRRT
LPLDIAKTLAGNGFLYLTAPDELA-EKAEQSHLLTL*
